sudo: required
language: generic
services:
  - docker
  - mysql
  - postgresql
  - memcached
env:
  - HHVM_VERSION=3.18-lts-latest
  - HHVM_VERSION=latest
before_install:
  - mysql < tests/sql/mysql/create_test_database.sql
  - mysql -e 'SHOW DATABASES'
  - mysql -e 'SHOW TABLES' phpunit
  - psql -U postgres < tests/sql/postgresql/create_test_database.sql
  - echo "localhost:5432:phpunit:zframework:i-am-a-walrus" > ~/.pgpass
  - echo '\d' | psql --user=zframework --host=localhost phpunit
install:
  - docker pull hhvm/hhvm:$HHVM_VERSION
script:
  - docker run -it -p 3606:3606 -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.build.sh
