sudo: required
language: generic
services:
  - docker
env:
  - HHVM_VERSION=latest
install:
  - docker pull zerodiv/hhvm:$HHVM_VERSION
script:
  - docker run -it -e GITHUB_TOKEN=$GITHUB_TOKEN -v $(pwd):/var/source zerodiv/hhvm:$HHVM_VERSION /var/source/.build.sh
