sudo: required
language: generic
services:
  - docker
  - postgresql
env:
  - HHVM_VERSION=3.18-lts-latest
  - HHVM_VERSION=latest
before_install:
  - psql -U postgres < tests/sql/postgresql/create_test_database.sql
  - echo "localhost:5432:phpunit:zframework:i-am-a-walrus" > ~/.pgpass
  - echo '\d' | psql --user=zframework --host=localhost phpunit
install:
  - docker pull hhvm/hhvm:$HHVM_VERSION
script:
  - docker run -it -v $(pwd):/var/source hhvm/hhvm:$HHVM_VERSION /var/source/.build.sh
